### ISSUE TITLE
CSS的一些技巧总结

### ISSUE THREAD

**Issue by SuGod** [SuGod/SuGod.github.io#2]

**Comment by SuGod** [comment]
bootstrap 中的栅格.  ``.row`` 下的两个 col 等高:
1. 奇技淫巧...
```css
col-xx{
    height:0;
    padding-bottom:100%;
}
```
2. 使用flex
```css
.ibox-content > .row {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    flex-wrap: wrap;
}
.ibox-content > .row > [class*='col-'] {
    display: flex;
    flex-direction: column;
}
```
